"""
Roadmap seed data and utilities.
"""
from datetime import datetime
from sqlalchemy.orm import Session
from app.models.database import RoadmapItem, RoadmapCategory, RoadmapStatus


SEED_ROADMAP_ITEMS = [
    # ─── Document & Content (PandaDoc / Notion) — 8 public ───
    {
        "title": "Real-Time Document Collaboration",
        "description": "Multiple team members can edit proposals and SOWs simultaneously with live cursors, conflict resolution, and presence indicators.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 1,
        "icon_name": "DocumentTextIcon",
        "inspired_by": "PandaDoc, Notion",
    },
    {
        "title": "Template Marketplace",
        "description": "Browse and use community-created templates for proposals, contracts, NDAs, and project plans. Share your own templates with the community.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 2,
        "icon_name": "RectangleStackIcon",
        "inspired_by": "Notion, PandaDoc",
    },
    {
        "title": "E-Signatures & Approval Workflows",
        "description": "Send documents for legally-binding e-signatures. Track signature status, set signing order, and automate follow-up reminders.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 3,
        "icon_name": "PencilSquareIcon",
        "inspired_by": "PandaDoc, DocuSign",
    },
    {
        "title": "AI Document Writer",
        "description": "Generate entire document sections from your scope tree data. AI understands your project context and writes proposals, technical specs, and summaries.",
        "category": "document_content",
        "status": "in_progress",
        "is_public": True,
        "order_index": 4,
        "icon_name": "SparklesIcon",
        "inspired_by": "Notion AI",
    },
    {
        "title": "Interactive Pricing Tables",
        "description": "Embed dynamic pricing tables in documents that auto-calculate totals. Clients can select line items and see real-time cost breakdowns.",
        "category": "document_content",
        "status": "shipped",
        "is_public": True,
        "order_index": 5,
        "icon_name": "TableCellsIcon",
        "inspired_by": "PandaDoc",
    },
    {
        "title": "Document Analytics & Viewer Tracking",
        "description": "See who opened your document, how long they spent on each page, and which sections they revisited. Get notified the moment a client views your proposal.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 6,
        "icon_name": "ChartBarIcon",
        "inspired_by": "PandaDoc",
    },
    {
        "title": "Content Library & Reusable Snippets",
        "description": "Save approved paragraphs, clauses, and media blocks to a shared content library. Drag snippets into any document to maintain consistency across proposals.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 7,
        "icon_name": "RectangleStackIcon",
        "inspired_by": "PandaDoc",
    },
    {
        "title": "Custom Branding & White Labeling",
        "description": "Apply your company's logo, colors, and fonts to all generated documents. Create branded templates that match your corporate identity.",
        "category": "document_content",
        "status": "planned",
        "is_public": True,
        "order_index": 8,
        "icon_name": "PaintBrushIcon",
        "inspired_by": "PandaDoc",
    },

    # ─── Team Communication (Slack) — 7 public ───
    {
        "title": "Rich Messaging with Media",
        "description": "Share images, files, code snippets, and screen recordings directly in project channels. Drag-and-drop or paste from clipboard.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 1,
        "icon_name": "ChatBubbleLeftRightIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "Threaded Conversations",
        "description": "Reply in threads to keep discussions organized. Threads auto-link to scope tree nodes so decisions are traced to their context.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 2,
        "icon_name": "ChatBubbleOvalLeftEllipsisIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "@Mentions & Reactions",
        "description": "Tag team members with @mentions to notify them. React to messages with emoji. Pin important decisions for quick reference.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 3,
        "icon_name": "AtSymbolIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "Project Activity Feed",
        "description": "A unified feed showing all project activity — scope changes, document edits, messages, and decisions — in chronological order.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 4,
        "icon_name": "BellAlertIcon",
        "inspired_by": "Slack, Linear",
    },
    {
        "title": "Voice & Video Huddles",
        "description": "Start instant audio or video huddles from any project channel. Share your screen, draw on a whiteboard, and record meetings for teammates who miss them.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 5,
        "icon_name": "DevicePhoneMobileIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "Scheduled Messages & Reminders",
        "description": "Schedule messages to send later across time zones. Set personal reminders on any message or scope tree node to follow up at the right time.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 6,
        "icon_name": "ClockIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "Status Updates & Do Not Disturb",
        "description": "Set custom status messages with emoji. Enable Do Not Disturb to pause notifications during focus time. Schedule availability windows for your team.",
        "category": "team_communication",
        "status": "planned",
        "is_public": True,
        "order_index": 7,
        "icon_name": "BellAlertIcon",
        "inspired_by": "Slack",
    },

    # ─── Project Management (ClickUp / Jira) — 8 public ───
    {
        "title": "Sprint Planning & Cycles",
        "description": "Organize work into time-boxed sprints. Set sprint goals, track velocity, and run retrospectives — all connected to your scope tree.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 1,
        "icon_name": "ArrowPathIcon",
        "inspired_by": "Jira, Linear",
    },
    {
        "title": "Whiteboard & Visual Planning",
        "description": "Free-form whiteboard for brainstorming and visual planning. Draw, sticky-note, and diagram — then convert ideas into scope tree nodes.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 2,
        "icon_name": "PaintBrushIcon",
        "inspired_by": "ClickUp, Miro",
    },
    {
        "title": "Workflow Automations",
        "description": "Create if-this-then-that automations. Auto-assign reviewers, move cards on status change, send notifications, and trigger exports.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 3,
        "icon_name": "BoltIcon",
        "inspired_by": "ClickUp, Zapier",
    },
    {
        "title": "Time Tracking & Estimation",
        "description": "Track time spent on scope tree nodes and planning cards. Compare estimates vs actuals. Generate utilization reports per team member.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 4,
        "icon_name": "ClockIcon",
        "inspired_by": "ClickUp, Jira",
    },
    {
        "title": "Multiple Board Views",
        "description": "View your project as Kanban board, Gantt chart, timeline, table, or calendar. Switch views without losing context.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 5,
        "icon_name": "ViewColumnsIcon",
        "inspired_by": "ClickUp, Notion",
    },
    {
        "title": "Kanban Planning Board",
        "description": "Drag-and-drop kanban board derived from your scope tree. Assign team members, set priorities, and track progress visually.",
        "category": "project_management",
        "status": "shipped",
        "is_public": True,
        "order_index": 6,
        "icon_name": "Squares2X2Icon",
        "inspired_by": "ClickUp, Jira",
    },
    {
        "title": "Custom Fields & Properties",
        "description": "Add custom fields to scope tree nodes and planning cards — dropdowns, dates, numbers, labels, and formulas. Filter and group by any field.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 7,
        "icon_name": "TableCellsIcon",
        "inspired_by": "ClickUp, Jira",
    },
    {
        "title": "Dependencies & Blocker Tracking",
        "description": "Define task dependencies (finish-to-start, start-to-start). Visualize the critical path and get alerts when blockers risk delaying delivery.",
        "category": "project_management",
        "status": "planned",
        "is_public": True,
        "order_index": 8,
        "icon_name": "ArrowsRightLeftIcon",
        "inspired_by": "Jira, ClickUp",
    },

    # ─── Platform & Infrastructure — 4 public + 3 internal ───
    {
        "title": "Plugin & Extension System",
        "description": "Build and install custom plugins to extend Hojaa. Create custom export formats, AI prompts, and integrations with your internal tools.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": True,
        "order_index": 1,
        "icon_name": "PuzzlePieceIcon",
        "inspired_by": "Notion, VS Code",
    },
    {
        "title": "Advanced Analytics Dashboard",
        "description": "Deep analytics on project health, team velocity, scope creep trends, and AI usage. Export reports for stakeholder updates.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": True,
        "order_index": 2,
        "icon_name": "ChartBarIcon",
        "inspired_by": "ClickUp, Jira",
    },
    {
        "title": "Mobile App (iOS & Android)",
        "description": "Review scope trees, approve changes, and chat with your team on the go. Push notifications for important updates.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": True,
        "order_index": 3,
        "icon_name": "DevicePhoneMobileIcon",
        "inspired_by": "Slack, Linear",
    },
    {
        "title": "Audit Logs & Compliance",
        "description": "Full audit trail of every action taken in your workspace. Export logs for SOC 2 and ISO 27001 compliance. Set retention policies per org.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": True,
        "order_index": 4,
        "icon_name": "DocumentTextIcon",
        "inspired_by": "Jira, Slack",
    },
    # Internal-only items
    {
        "title": "Security Hardening Phase 2",
        "description": "CSP nonce rotation, sub-resource integrity checks, and enhanced SQL injection protection.",
        "category": "platform_infrastructure",
        "status": "in_progress",
        "is_public": False,
        "order_index": 100,
    },
    {
        "title": "Rate Limiting v2 — Per-User Quotas",
        "description": "Per-user and per-org rate limiting with Redis token bucket. Admin UI for quota management.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": False,
        "order_index": 101,
    },
    {
        "title": "API Key Scoping & Rotation",
        "description": "Fine-grained scope editing for API keys, key rotation without downtime, and usage analytics per key.",
        "category": "platform_infrastructure",
        "status": "planned",
        "is_public": False,
        "order_index": 102,
    },

    # ─── Integrations — 7 public ───
    {
        "title": "Slack Integration",
        "description": "Two-way sync with Slack. Get notified of scope changes in your channel. Create scope items from Slack messages.",
        "category": "integrations",
        "status": "shipped",
        "is_public": True,
        "order_index": 1,
        "icon_name": "HashtagIcon",
        "inspired_by": "Slack",
    },
    {
        "title": "Jira Bi-Directional Sync",
        "description": "Sync scope tree nodes and planning cards with Jira issues. Changes in either system are reflected in real-time.",
        "category": "integrations",
        "status": "shipped",
        "is_public": True,
        "order_index": 2,
        "icon_name": "ArrowsRightLeftIcon",
        "inspired_by": "Jira",
    },
    {
        "title": "GitHub Integration",
        "description": "Link scope tree nodes to GitHub issues and PRs. Auto-update node status when PRs are merged.",
        "category": "integrations",
        "status": "planned",
        "is_public": True,
        "order_index": 3,
        "icon_name": "CodeBracketIcon",
        "inspired_by": "GitHub, Linear",
    },
    {
        "title": "Figma Plugin",
        "description": "Import design specifications from Figma frames. Auto-generate scope tree nodes from design components with AI analysis.",
        "category": "integrations",
        "status": "planned",
        "is_public": True,
        "order_index": 4,
        "icon_name": "SwatchIcon",
        "inspired_by": "Figma",
    },
    {
        "title": "Zapier & Webhooks",
        "description": "Connect Hojaa to 5,000+ apps through Zapier. Configure custom webhooks for any event in the system.",
        "category": "integrations",
        "status": "planned",
        "is_public": True,
        "order_index": 5,
        "icon_name": "LinkIcon",
        "inspired_by": "Zapier",
    },
    {
        "title": "Confluence & Notion Import",
        "description": "Migrate existing documentation from Confluence or Notion into Hojaa. Preserves page hierarchy, rich text, and embedded media.",
        "category": "integrations",
        "status": "planned",
        "is_public": True,
        "order_index": 6,
        "icon_name": "DocumentTextIcon",
        "inspired_by": "Confluence, Notion",
    },
    {
        "title": "Google Workspace Integration",
        "description": "Attach Google Docs, Sheets, and Slides to scope tree nodes. Embed live previews and sync changes bidirectionally.",
        "category": "integrations",
        "status": "planned",
        "is_public": True,
        "order_index": 7,
        "icon_name": "LinkIcon",
        "inspired_by": "Slack, ClickUp",
    },
]


def seed_roadmap_items(db: Session) -> int:
    """Seed the roadmap with initial items. Returns count of items created."""
    existing = db.query(RoadmapItem).count()
    if existing > 0:
        return 0

    count = 0
    for item_data in SEED_ROADMAP_ITEMS:
        item = RoadmapItem(
            title=item_data["title"],
            description=item_data.get("description"),
            category=RoadmapCategory(item_data["category"]),
            status=RoadmapStatus(item_data["status"]),
            is_public=item_data.get("is_public", True),
            order_index=item_data.get("order_index", 0),
            icon_name=item_data.get("icon_name"),
            inspired_by=item_data.get("inspired_by"),
            shipped_at=datetime.utcnow() if item_data["status"] == "shipped" else None,
        )
        db.add(item)
        count += 1

    db.commit()
    return count
